In [1]:
import numpy as np

In [2]:
arr=np.array([10,20,30])
arr

array([10, 20, 30])

In [3]:
arr1=np.array([1.0,20,30])
arr1

array([ 1., 20., 30.])

In [4]:
arr2=np.array([10,'a'])
arr2

array(['10', 'a'], dtype='<U21')

In [5]:
arr3=np.arange(1,11)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr3.size

10

In [8]:
arr3.shape

(10,)

In [9]:
arr2d=np.arange(1,13).reshape((4,3))
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
arr.ndim

1

In [11]:
arr2d.ndim


2

In [14]:
arr3d=np.arange(1,25).reshape((2,4,3))
arr3d


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [20]:
arr3d=np.arange(1,25).reshape((2,4,3))
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [21]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
arr2d[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [24]:
arr3= np.arange(1,43).reshape(6,7)
arr3

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42]])

In [25]:
arr3[1:4,1:4]

array([[ 9, 10, 11],
       [16, 17, 18],
       [23, 24, 25]])

In [29]:
arr3[:,:-1]

array([[ 1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13],
       [15, 16, 17, 18, 19, 20],
       [22, 23, 24, 25, 26, 27],
       [29, 30, 31, 32, 33, 34],
       [36, 37, 38, 39, 40, 41]])

In [33]:
arr3[:,-1]

array([ 7, 14, 21, 28, 35, 42])

In [36]:
arr3[[0,2,5]]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [15, 16, 17, 18, 19, 20, 21],
       [36, 37, 38, 39, 40, 41, 42]])

In [43]:
arr3[[0,2,5]]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [15, 16, 17, 18, 19, 20, 21],
       [36, 37, 38, 39, 40, 41, 42]])

In [44]:
arr3[:,-1]

array([ 7, 14, 21, 28, 35, 42])