In [2]:
import numpy as np

In [19]:
np.random.random()

0.05637444891098509

In [26]:
team1= np.random.randint(0,36,10)
team1

array([15, 32, 15,  9, 10, 23, 26,  4,  6,  6], dtype=int32)

In [5]:
np.random.randint(0,36,(4,5))

array([[ 2, 17,  7, 19,  7],
       [30, 14, 35,  5, 23],
       [ 8, 31, 27,  5, 15],
       [ 0, 10, 35, 34, 10]], dtype=int32)

In [39]:
np.random.seed(200)
np.random.randint(0,100,2)

array([26, 16], dtype=int32)

In [49]:
np.random.rand()

0.62448816736063

In [53]:
np.random.randn(10)

array([-0.15696957, -1.73564499,  0.71253835, -1.61930378, -1.75045772,
        0.16183351, -1.50293978,  1.13368414, -0.29787964, -0.60186382])

In [9]:
dice= np.arange(1,7)

In [10]:
dice

array([1, 2, 3, 4, 5, 6])

In [57]:
np.random.permutation(dice)

array([3, 6, 2, 4, 5, 1])

In [62]:
np.random.choice(dice)

np.int64(6)

In [63]:
np.sin(np.radians(30))

np.float64(0.49999999999999994)